name: Pre-Release

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        run: |
          print "Probando el pre-release" 